INSERT INTO Serie VALUES ('','');
INSERT INTO Serie VALUES ('Código da série','Descrição da séria');
INSERT INTO Serie VALUES ('61','1º Ano');
INSERT INTO Serie VALUES ('62','2º Ano');
INSERT INTO Serie VALUES ('63','3º Ano');
INSERT INTO Serie VALUES ('64','4º Ano');
INSERT INTO Serie VALUES ('65','5º Ano');
INSERT INTO Serie VALUES ('66','6º Ano');
INSERT INTO Serie VALUES ('67','7º Ano');
INSERT INTO Serie VALUES ('68','8º Ano');
INSERT INTO Serie VALUES ('69','9º Ano');
INSERT INTO Serie VALUES ('76','4º Ano - NCM');
INSERT INTO Serie VALUES ('77','7º Ano - NJM');
INSERT INTO Serie VALUES ('81','Realfabetização 1');
INSERT INTO Serie VALUES ('83','Realfabetização 2');
INSERT INTO Serie VALUES ('84','Aceleração 1');
INSERT INTO Serie VALUES ('87','Aceleração 2A');
INSERT INTO Serie VALUES ('89','Aceleração 3');
INSERT INTO Serie VALUES ('99','Total');
